name: pokedex
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4

  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.18.1
  stream_transform: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
